name: idcard
description: "ID Card Generator App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0

  # UI / Animation
  flutter_animate: ^4.5.0
  lottie: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flip_card: ^0.7.0

  # Data / Files (Web-safe)
  excel: ^4.0.2
  pdf: ^3.10.7
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0

  # Conditional platform usage ONLY
  file_picker: ^8.0.3
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo/logo.png

  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true

  image_path: "assets/images/logo/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
